### ISSUE TITLE
PageFl/p Comics not working

### ISSUE THREAD

**Issue by Bubblyme7** [oseparovic/comic_selectors#184] opened 2024-05-24 03:23 UTC
In the PageFl/p app Back to BC, Frazz , Wizard of Id, Dogs of C Kennel, & Fox Trot Classics, all say "Image not found" for all or most of the comics (I went through some of Frazz and found a few days that displayed correctly). I can view them online, but then I lose my place in the app as the app stays where it is while I continue online, and there are ads, etc.

**Comment by oseparovic** [comment] 2024-06-09 18:23
Duplicate of #182

**Closed by oseparovic** 2024-06-09 18:23 UTC
