### ISSUE TITLE
ArcaMax

### ISSUE THREAD

**Issue by joem5636** [oseparovic/comic_selectors#132] opened 2022-06-15 10:37 UTC
Comics on ArcaMax not loading. Bizarro is just one.

Webpage not available
The webpage at https://www.arcamax.com/thefunnies/bizarro/ could not be loaded because:

net::ERR_CONNECTION_REFUSED

**Comment by kc2cbd** [comment] 2022-12-18 22:09
It works on my device.

**Comment by oseparovic** [comment] 2022-12-19 20:15
confirmed, works for me as well. Closing

**Closed by oseparovic** 2022-12-19 20:15 UTC
