### ISSUE TITLE
Many comics not opening 

### ISSUE THREAD

**Issue by MarkH58** [oseparovic/comic_selectors#147] opened 2022-11-22 13:18 UTC
BC,Garfield, Calvin and Hobbs, Foxtrot and Ziggy not opening since, at least the 20th November 2021

**Comment by appstronautstudios** [comment] 2022-11-22 16:42
duplicate of #146

**Comment by oseparovic** [comment] 2022-11-22 16:45
Duplicate of #146

**Closed by oseparovic** 2022-11-22 16:45 UTC
