### ISSUE TITLE
"Image not found" - calvin & hobbs

### ISSUE THREAD

**Issue by gbtate** [oseparovic/comic_selectors#144] opened 2022-11-20 13:29 UTC

**Comment by oseparovic** [comment] 2022-11-22 16:48
Duplicate of #146

**Closed by oseparovic** 2022-11-22 16:48 UTC

**Comment by gbtate** [comment] 2022-11-22 17:15
Nothing resolved at all. Issue persists.

(Mr) Gayle B Tate
G. B. Tate & Sons Fine Art

www.gbtate.com
Email:  ***@***.***
